### ISSUE TITLE
Rewriting it in c instead of python

### ISSUE THREAD

**Issue by pickfire** [gaenserich/hostsblock#12]

**Comment by gaenserich** [comment]
Problematic, since I don't know C. At present, I've still been using bash plus grep, sed, and company. If performance is a concern, the pre-alpha has much improved performance (using grep as much as possible instead of sed does wonders). However, as it stands, it would take a completely different project with a completely different principle author to impliment hostsblock's functionality into C.

**Comment by pickfire** [comment]
So, would it use python or perl?

**Comment by gaenserich** [comment]
At this point I'm using bash, since I'm most familiar with it. I've been
working to make it feature complete before switching to a different
language. Perhaps 2.0 will be in python or perl.
Am 23.04.2015 09:16 schrieb "Ivan Tham" <notifications@github.com>:

**Comment by pickfire** [comment]
I hope it will be in python so I do not need to install that much packages. Thanks.

**Comment by gaenserich** [comment]
A switch from bash to python will, if anything, cause more packages to need
to be installed. As it stands, all the hard dependencies rely on standard
utilities that you _should_ already have installed. However, Python and
Perl already have most of the functions required for hostsblock already
built in, so I doubt either will require many, if any, additional modules
to function.

Jacob A. van der Kolk <http://personal.psu.edu/jav209>
Lecturer in German
Ph.D. Candidate in German Literature and Culture, ABD
Department of Germanic and Slavic Languages and Literatures
The Pennsylvania State University
jav209@psu.edu
PGP Public Key <http://www.personal.psu.edu/jav209/jvdk.gpg> (plaintext
<http://www.personal.psu.edu/jav209/jvdk.asc>)

2015-04-23 10:10 GMT-04:00 Ivan Tham <notifications@github.com>:
