### ISSUE TITLE
hosts.block file has now 2 erroneous entries

### ISSUE THREAD

**Issue by Sadi58** [gaenserich/hostsblock#24]
After the latest commits I can see better processing in producing the `hosts.block` file with only 2 exceptions.
I have the following two lines as the 1st and 3rd entries:
```
0.0.0.0 0.0.0.0
0.0.0.0 0.0.0.0 www.zergnet.com
```
I don't think this is caused by the fact that I use `0.0.0.0` (which works fine for me) instead of `127.0.0.1` (which creates a little larger file).

**Comment by gaenserich** [comment]
I've reproduced it. It appears to be from a couple bad lines in two block lists, from hostsblock.db:
`0.0.0.0 0.0.0.0 ! http://sysctl.org/cameleon/hosts`
`0.0.0.0 0.0.0.0 www.zergnet.com ! http://winhelp2002.mvps.org/hosts.zip`
Since this is an upstream error with no impact on functionality (the first line redirects any call to 0.0.0.0 back to 0.0.0.0 and the second does the same with additionally zergnet.com) and probably no perceivable impact on performance (two lines out of, on my box, 2 million entries won't do much), I'm not inclined to add complexity to take care of these errors. Do keep an eye out for other faulty lines, however. If a significant number of them emerge, we will add some code to spruce them up.

**Comment by Sadi58** [comment]
Fair enough.
The only logical thing to do is to inform the maintainers of these 2 lists then.
I guess www.zergnet.com should also be blacklisted, so we should only remove the leading 0.0.0.0 in that line.
