### ISSUE TITLE
Add configuration option to use a different port

### ISSUE THREAD

**Issue by Dialga** [gaenserich/hostsblock#86]
I'd like to run my http server using port 80, currently this is not possible because kwakd occupies port 80.
Is it possible to add a configuration option to use a different port for kwakd?
Also the documentation is rather lacking in describing setting kwakd for use with hostsblock.

I've tried redirecting blocked hosts to 127.0.0.1:78 and running `kwakd -p 78` but it has no effect.

**Comment by gaenserich** [comment]
This is a limitation of /etc/hosts; there's no way to specify ports therein
(and port 80 is assumed by browsers and http clients since it is the
standard http port). You could perhaps create an iptables rule that
redirects all port 80 requests to 78 under certain conditions, or make your
http server work on a different port.

Jake van der Kolk, Ph.D.
http://personal.psu.edu/jav209

Dialga <notifications@github.com> schrieb am Do., 10. Mai 2018, 22:24:
